name: Deploy Server

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - apps/server/**

jobs:
  deploy:
    environment: production

    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write
      id-token: write # Required for GitHub OIDC

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        working-directory: apps/web
        run: pnpm install

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
          secrets: |
            DATABASE_URL
            BETTER_AUTH_SECRET
            BETTER_AUTH_URL
          variables:
            NODE_ENV: ${{ env.NODE_ENV }}
            CORS_ORIGIN: ${{ env.CORS_ORIGIN }}
          workingDirectory: apps/server
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: ${{ vars.NODE_ENV }}
          CORS_ORIGIN: ${{ vars.CORS_ORIGIN }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}

      - name: Print deployment-url
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL
